<?php
include('config_db.php');
include('config_qyk.php');
/*----基础配置更新于2015-11-24 23:52:00----*/
define('setup_customer_bcat','未归类,QQ客服,Skype客服,其它客服');
define('setup_errortag','[!--标签错误--]');
define('setup_pagetag','{article_page_tag}');
define('setup_themefile','theme_data.txt');
define('setup_cachetype','html');
define('setup_temptype','html');
define('setup_prefix','{:');
define('setup_suffix','}');
define('setup_filerand',time());
define('setup_am_page',20);
define('setup_am_more',true);
define('setup_am_super',false);
define('setup_am_super_pass','');
define('setup_am_setup_cata','setup|系统综合,tool|侧栏工具,upload|上传设置,smtp|邮件设置,theme|主题设置');
define('setup_webfolder','template/');
define('setup_upfolder','upload/');
define('setup_uptemp','temp/');
define('setup_uploadtag','{upload_path_tag}');
define('setup_editfile_bak',false);
define('setup_static_file','httpd.ini');
define('setup_theme_artnum',1000);
define('setup_login_error_num',5);
define('setup_login_error_time',600);
define('setup_tempcache_md5',false);
define('setup_websetup_del',true);
?>